# # For more information: https://laravel.com/docs/sail
# version: '2'
# services:
#     laravel.test:
#         # build:
#         #     context: ./vendor/laravel/sail/runtimes/8.0
#         #     dockerfile: Dockerfile
#         # image: sail-8.0/app
#         tty: true
#         image: docker.io/bitnami/laravel:7-debian-10
#         ports:
#             - '3000:3000'
#         # environment:
#         #     WWWUSER: '${WWWUSER}'
#         #     LARAVEL_SAIL: 1
#         volumes:
#             # - '.:/var/www/html'
#             - './:/app'
#         # networks:
#         #     - sail
#         environment:
#             DB_HOST : mariadb
#             DB_USERNAME : root
#             DB_DATABASE : vueapp
#             DB_PASSWORD : 
#         depends_on:
#             - mariadb
#             # - redis
#             # - selenium
#     # selenium:
#     #     image: 'selenium/standalone-chrome'
#     #     volumes:
#     #         - '/dev/shm:/dev/shm'
#     #     networks:
#     #         - sail
#     #     depends_on:
#     #         - laravel.test
#     # mysql:
#     #     image: 'mysql:8.0'
#     #     ports:
#     #         - '${FORWARD_DB_PORT:-3306}:3306'
#     #     environment:
#     #         MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
#     #         MYSQL_DATABASE: '${DB_DATABASE}'
#     #         MYSQL_USER: '${DB_USERNAME}'
#     #         MYSQL_PASSWORD: '${DB_PASSWORD}'
#     #         MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#     #     volumes:
#     #         - 'sailmysql:/var/lib/mysql'
#     #     networks:
#     #         - sail
#     mariadb:
#         image: mariadb
#         restart: always
#         environment: 
#             MYSQL_DATABASE:  vueapp
#             MYSQL_ROOT_PASSWORD: 
#         volumes:
#             - ./app/data:/var/lib/mysql
#         ports: 
#             - 3306:3306
#     # redis:
#     #     image: 'redis:alpine'
#     #     ports:
#     #         - '${FORWARD_REDIS_PORT:-6379}:6379'
#     #     volumes:
#     #         - 'sailredis:/data'
#     #     networks:
#     #         - sail
#     # memcached:
#     #     image: 'memcached:alpine'
#     #     ports:
#     #         - '11211:11211'
#     #     networks:
#     #         - sail
#     # mailhog:
#     #     image: 'mailhog/mailhog:latest'
#     #     ports:
#     #         - 1025:1025
#     #         - 8025:8025
#     #     networks:
#     #         - sail
# # networks:
# #     sail:
# #         driver: bridge
# # volumes:
# #     sailmysql:
# #         driver: local
# #     sailredis:
# #         driver: local
version: '2'

services:
  mariadb:
    image: mariadb
    restart: always
    environment: 
      MYSQL_DATABASE: vueapp
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - ./app/data:/var/lib/mysql
    ports: 
      - 3306:3306
  # myapp:
  #   tty: true
  #   image: docker.io/bitnami/laravel:7-debian-10
  #   environment:
  #     - DB_HOST=mariadb
  #     - DB_USERNAME=root
  #     - DB_DATABASE=vueapp
  #     - DB_PASSWORD=
  #   depends_on:
  #     - mariadb
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./:/app
    # privileged: true # Privileged mode could be required to run this container under Windows
